// <auto-generated />
using System;
using FCTAssignmentApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FCTAssignmentApp.Migrations
{
    [DbContext(typeof(CustomerContext))]
    [Migration("20191102054158_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FCTAssignmentApp.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(255)")
                        .HasMaxLength(255);

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("FCTAssignmentApp.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Item 1",
                            Price = 10.550000000000001
                        },
                        new
                        {
                            Id = 2,
                            Name = "Item 2",
                            Price = 25.989999999999998
                        },
                        new
                        {
                            Id = 3,
                            Name = "Item 3",
                            Price = 5.1500000000000004
                        },
                        new
                        {
                            Id = 4,
                            Name = "Test item 1",
                            Price = 99.549999999999997
                        },
                        new
                        {
                            Id = 5,
                            Name = "Test item 2",
                            Price = 20.300000000000001
                        },
                        new
                        {
                            Id = 6,
                            Name = "Test item 3",
                            Price = 9.9900000000000002
                        },
                        new
                        {
                            Id = 7,
                            Name = "Abc item 1",
                            Price = 159.99000000000001
                        },
                        new
                        {
                            Id = 8,
                            Name = "Abc Item 2",
                            Price = 11.99
                        },
                        new
                        {
                            Id = 9,
                            Name = "Running Shoes",
                            Price = 59.990000000000002
                        });
                });

            modelBuilder.Entity("FCTAssignmentApp.Models.Purchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("OrderStatus")
                        .HasColumnType("int");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("FCTAssignmentApp.Models.Purchase", b =>
                {
                    b.HasOne("FCTAssignmentApp.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.HasOne("FCTAssignmentApp.Models.Customer", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
